# PyTorch Tensor Tutorial

In [2]:
import torch

#### Zero tensors

In [6]:
# 1-d zero tensor
zeros = torch.zeros(3)
print(zeros)

# 2-d zero tensor
zeros = torch.zeros((2, 3))
print(zeros)

tensor([0., 0., 0.])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


#### Ones tensors

In [8]:
# 1-d '1' tensors
ones = torch.ones(3)
print(ones)

# 2-d '1' tensors
ones = torch.ones((2, 3))
print(ones)

tensor([1., 1., 1.])
tensor([[1., 1., 1.],
        [1., 1., 1.]])


#### Random Tensor initialization

In [9]:
# initialization from python list
t1 = torch.tensor([1, 2, 3, 4])
print(t1)

tensor([1, 2, 3, 4])


## Storage of PyTorch Tensors

Under the hood, PyTorch Tensors are physically stored in consecutive cells for optimized performance. 

In [10]:
mat_a = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(mat_a)

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])


We can use `.storage()` on the tensor to retrive the underlying sequence

In [11]:
mat_storage = mat_a.storage()
print(mat_storage)

 1
 2
 3
 4
 5
 6
 7
 8
 9
[torch.LongStorage of size 9]


Here the matrix is physically stored in a row-major order. PyTorch uses stride to retrieve the element. `.stride()` can be used to get the stride of the tensor.

In [12]:
stride = mat_a.stride()
print(stride)

(3, 1)


The tuple `(3,1)` means, the next row can be found by skipping 3 elements and next column can be found by skipping 1.
 In other words, the index for mat_a[1, 2] is calculated as `stride[0]*1 + stride[1]*2`.

**Transposing** a matrix doesnot change the underlying physical representation of the tensor but creates a view with a different stride.

In [15]:
mat_a_t = mat_a.t()
print(mat_a_t)
stride_t = mat_a_t.stride()
print(stride_t)

tensor([[1, 4, 7],
        [2, 5, 8],
        [3, 6, 9]])
(1, 3)


#### Transfer a tensor to GPU

We can transfer the tensor to a GPU in one of the following ways

In [20]:
mat_a_gpu = mat_a.cuda()
mat_a_gpu = mat_a.to('cuda')
mat_a_gpu = mat_a.to('cuda:0') #Indexing the GPU
mat_a_gpu = mat_a.cuda(0) # Indexing the GPU

In [21]:
mat_a_t_gpu = mat_a_t.cuda()

In [22]:
mat_a_t

tensor([[1, 4, 7],
        [2, 5, 8],
        [3, 6, 9]])

#### Serializing a tensor

**Using tensor.save()**

In [41]:
torch.save(mat_a, 'mat_a.t')

**Using HDF5** `h5py`

In [47]:
import h5py

# Writing

f = h5py.File('matrices.hdf5', 'w')
dset = f.create_dataset('mat_a', data=mat_a.numpy())
f.close()

# Reading

f = h5py.File('matrices.hdf5', 'r')
dset = f['mat_a']
last_points = dset[-2:]
print(last_points)
f.close()

[[4 5 6]
 [7 8 9]]


More to cover:
- dtypes
- Named Tensors
- NumPy Interoperability

# Exercises

1. Create a tensor `a` from `list(range(9))`. Predict and then check the size, offset, and stride.
 - Create a new tensor using `b = a.view(3,3)`. What does `view` do? Check that `a` and `b` share the same storage.
 - Create a tensorf `c = b[1:, 1:]`. Predict and then check the size, offset, and stride.

In [40]:
a = torch.tensor(list(range(9)))
print(a.shape)
print(a.storage_offset())
print(a.stride())

b = a.view(3, 3)
print(b)
print(b.storage())

c = b[1:, 1:]
print(c)
print(c.stride())
print(c.storage_offset())
print(c.size())

torch.Size([9])
0
(1,)
tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])
 0
 1
 2
 3
 4
 5
 6
 7
 8
[torch.LongStorage of size 9]
tensor([[4, 5],
        [7, 8]])
(3, 1)
4
torch.Size([2, 2])


In [36]:
b.stride()

(3, 1)

In [ ]:
t